/* USER actions */
export const USER_SIGN_UP_START = 'USER_SIGN_UP_START'
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS'
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE'

export const VERIFY_USER_START = 'VERIFY_USER_START'
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAILURE = 'VERIFY_USER_FAILURE'

export const USER_SIGN_IN_START = 'USER_SIGN_IN_START'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE'

export const USER_SIGN_OUT = 'USER_SIGN_OUT'

export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const ACCEPT_PAY_START = 'ACCEPT_PAY_START'
export const ACCEPT_PAY_SUCCESS = 'ACCEPT_PAY_SUCCESS'
export const ACCEPT_PAY_FAILURE = 'ACCEPT_PAY_FAILURE'

export const PASS_URL_PARAMS = 'PASS_URL_PARAMS'
export const CLEAR_URL_PARAMS = 'CLEAR_URL_PARAMS'
/* END of USER actions */

/* SALON actions */
export const ADD_SALON_START = 'ADD_SALON_START'
export const ADD_SALON_FAILURE = 'ADD_SALON_FAILURE'

export const UPDATE_SALON_START = 'UPDATE_SALON_START'
export const UPDATE_SALON_FAILURE = 'UPDATE_SALON_FAILURE'

export const PLACE_SALON_DATA = 'PLACE_SALON_DATA'

export const FETCH_TO_BILL_CLIENT_START = 'FETCH_TO_BILL_CLIENT_START'
export const FETCH_TO_BILL_CLIENT_SUCCESS = 'FETCH_TO_BILL_CLIENT_SUCCESS'
export const FETCH_TO_BILL_CLIENT_FAILURE = 'FETCH_TO_BILL_CLIENT_FAILURE'

export const RESET_TO_BILL_CLIENT_SUCCESS = 'RESET_TO_BILL_CLIENT_SUCCESS'

export const SAVE_SALON_RECEIPT_START = 'SAVE_SALON_RECEIPT_START'
export const SAVE_SALON_RECEIPT_SUCCESS = 'SAVE_SALON_RECEIPT_SUCCESS'
export const SAVE_SALON_RECEIPT_FAILURE = 'SAVE_SALON_RECEIPT_FAILURE'

export const COMPLETE_SALON_RECEIPT_START = 'COMPLETE_SALON_RECEIPT_START'
export const COMPLETE_SALON_RECEIPT_SUCCESS = 'COMPLETE_SALON_RECEIPT_SUCCESS'
export const COMPLETE_SALON_RECEIPT_FAILURE = 'COMPLETE_SALON_RECEIPT_FAILURE'

export const DELETE_SALON_PICTURE_START = 'DELETE_SALON_PICTURE_START'
export const DELETE_SALON_PICTURE_SUCCESS = 'DELETE_SALON_PICTURE_SUCCESS'
export const DELETE_SALON_PICTURE_FAILURE = 'DELETE_SALON_PICTURE_FAILURE'

export const DELETE_ORDER_START = 'DELETE_ORDER_START'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE'

export const FETCH_SALONS_FILTER_LIST_START = 'FETCH_SALONS_FILTER_LIST_START'
export const FETCH_SALONS_FILTER_LIST_SUCCESS = 'FETCH_SALONS_FILTER_LIST_SUCCESS'
export const FETCH_SALONS_FILTER_LIST_FAILURE = 'FETCH_SALONS_FILTER_LIST_FAILURE'
/* END of SALON actions */

/* BUSINESSES actions */
export const FETCH_BUSINESSES_LIST_START = 'FETCH_BUSINESSES_LIST_START'
export const FETCH_BUSINESSES_LIST_SUCCESS = 'FETCH_BUSINESSES_LIST_SUCCESS'
export const FETCH_BUSINESSES_LIST_FAILURE = 'FETCH_BUSINESSES_LIST_FAILURE'
/* END of BUSINESSES actions */


