/* USER actions */
export const FETCH_MODELS_LIST_START = 'FETCH_MODELS_LIST_START'
export const FETCH_MODELS_LIST_SUCCESS = 'FETCH_MODELS_LIST_SUCCESS'
export const FETCH_MODELS_LIST_FAILURE = 'FETCH_MODELS_LIST_FAILURE'

export const FETCH_MODEL_FIELDS_LIST_START = 'FETCH_MODEL_FIELDS_LIST_START'
export const FETCH_MODEL_FIELDS_LIST_SUCCESS = 'FETCH_MODEL_FIELDS_LIST_SUCCESS'
export const FETCH_MODEL_FIELDS_LIST_FAILURE = 'FETCH_MODEL_FIELDS_LIST_FAILURE'

export const FETCH_MODEL_FIELDS_FILTER_LIST_START = 'FETCH_MODEL_FIELDS_FILTER_LIST_START'
export const FETCH_MODEL_FIELDS_FILTER_LIST_SUCCESS = 'FETCH_MODEL_FIELDS_FILTER_LIST_SUCCESS'
export const FETCH_MODEL_FIELDS_FILTER_LIST_FAILURE = 'FETCH_MODEL_FIELDS_FILTER_LIST_FAILURE'
/* END of USER actions */
